car_price_calculation.settings:
  type: config_object
  label: 'Car price calculation Settings'
  mapping:
    fixed_price:
      type: float
      label: 'Fixed price'
    variable_price:
      type: float
      label: 'Variable price'
